




































































Epoch: 0001 | Iter: 3750 | G Loss: 0.89 | D Loss: 1.20 | MI: 1.48 | Real Acc: 75.00% | Fake Acc: 600.00%: 100%|█| 3750/3750 [02:20<00:00, 26.77it/






































































Epoch: 0002 | Iter: 3750 | G Loss: 0.91 | D Loss: 1.18 | MI: 1.54 | Real Acc: 68.75% | Fake Acc: 1300.00%: 100%|█| 3750/3750 [02:20<00:00, 26.62it
























































Epoch: 0003 | Iter: 3007 | G Loss: 0.88 | D Loss: 1.15 | MI: 1.60 | Real Acc: 81.25% | Fake Acc: 1200.00%:  80%|▊| 3007/3750 [01:54<00:28, 26.19it
Traceback (most recent call last):
  File "dd.py", line 250, in <module>
    MI = cat_loss(cat_pred, categ_code.argmax(-1))
  File "dd.py", line 243, in main
    categ_code = get_categorical(B, 10).to(args.device)
  File "/home/keonwookim/anaconda3/lib/python3.7/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/keonwookim/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 149, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA error: an illegal memory access was encountered